"""Cross-process constants shared between the in-IDA server and the proxy CLI.

These define the wire contract: changing a value here propagates to both
ends so they cannot drift out of sync.

There are two distinct TCP layers in this project; the constants below
cover layer 1 only:

1. **Layer 1 -- MCP host <-> proxy.** Optional, only present when the user
   runs ``ida-pro-mcp-headless`` with ``--transport streamable-http`` / ``--transport sse``.
   ``DEFAULT_REMOTE_PORT`` is the default for that listener.

2. **Layer 2 -- proxy <-> IDA plugin.** Always-on JSON-RPC HTTP between the
   proxy CLI and each running IDA. The TCP port is **not** declared here on
   purpose: every IDA process binds an ephemeral kernel-assigned port (see
   :class:`Server`) and advertises it via the per-session sidecar files in
   :mod:`.session`. Hardcoding a port would defeat multi-IDA support and
   wasn't useful even with one IDA (port-conflict diagnostics are clearer
   at the bind site).
"""
from __future__ import annotations

from typing import Final

DEFAULT_HOST: Final = "127.0.0.1"

# Default layer-1 port used when the proxy is exposed over HTTP. Layer 2
# (proxy <-> IDA) keeps using ephemeral ports per IDA process, so a fixed
# value here does *not* limit how many IDAs you can run concurrently. The
# choice (``13337``) is "leet" and unlikely to collide with the usual dev
# servers (3000/5000/8000/8080). Override with ``--port`` when needed.
DEFAULT_REMOTE_PORT: Final = 13337

# Timeout the *MCP host* (e.g. Cline, Cursor) should apply per tool call. The
# MCP config snippet generated by ``installer.print_mcp_config`` uses this.
# It is generous (30 minutes) because some IDA tools -- decompiling a large
# function on first access, structure inference -- legitimately take a while.
DEFAULT_TIMEOUT_S: Final = 1800

# Timeout the *transport* (the HTTP socket between proxy and IDA) uses. Much
# tighter than ``DEFAULT_TIMEOUT_S`` because a 30-minute socket wait makes
# IDA crashes / restarts indistinguishable from a slow operation. Five
# minutes covers any reasonable single tool call while still surfacing dead
# servers in human time.
DEFAULT_HTTP_TIMEOUT_S: Final = 300

# Identifier used as the FastMCP server name *and* as the default key in
# the rendered ``mcpServers`` config snippet. Kept short so the combined
# ``<server>_<tool>`` identifier (some MCP hosts cap this at 60 chars) stays
# under the limit even for our longest tool name. Users are free to rename
# the key in their own ``mcp.json`` -- this is just the default we hand them.
MCP_SERVER_NAME: Final = "ida-pro-mcp-headless"

HTTP_ENDPOINT_PATH: Final = "/mcp"
